recebe_dados_uart: recebe_envia_dados_uart.c comunicacao_uart.c trata_e_envia_dados_lora.c
	gcc -Wall recebe_envia_dados_uart.c comunicacao_uart.c trata_e_envia_dados_lora.c -o recebe_envia_dados_uart -lpaho-mqtt3c
